# ==GoldenDict Command-Line Version (gdcl) Configuration File==
#
# By default, gdcl will look for this file in the config folder under the
# user's home directory (~/.config/gdcl/) or in the $XDG_CONFIG_DIRS 
# (/etc/xdg/gdcl). If it can't find a file named config.yml in these default 
# location, it will look for it in the current working directory. If 
# config.yml cannot be found in any of the above locations, the program will 
# abort with an error message explaining the situation.


# ==Configuration options==

# Location of GoldenDict dictionaries folder
# Note: This can be set to any arbitrary location containing dictionary files
:dict_dir: "~/.goldendict/dic/"

# Group name (at the moment this should be the name of a subfolder in your 
# GoldenDict dictionary directory)
:group: ""

# Default group
# Set this if you want gdcl to search a particular group of dictionaries by
# default when no group is specified either interactively or on the 
# command-line
:default_group: ""

# Keyword to search for
:kword: ""

# Set to false for non-interactive search (e.g. to pipe the search results)
# Defaults to non-interactive search if group and keyword are specified as 
# command-line parameters
:interactive_search: true

# Set to false to turn off header and footer information (i.e. dictionary 
# name, number of hits for search term)
:header_footer: true

# Don't prompt to open results in pager
# Set this to true to turn off the pager prompt for all searches
:pager_off: false

# Enable case insensitive search for all searches
# Set this to true if you want searches for the word "dog" to return
# results for "dog", "Dog", and "DOG"
:case_off: false

# Enable logging of search terms (off by default)
# :history: true

# Alternate location of search history logfile
# Default is gdcl config folder, i.e.: ~/.config/gdcl
# :logfile: "~/example/path"

# Search pattern (specify a pattern to search for, default is headwords 
# starting with keyword; include regex between // slashes)
# :search_term: /^#{kword}/
# :search_term: /^#{kword}$/    # searches for strictly matching headwords

# optionally exlude the following dictionaries, separated by commas 
# (use original filename without dsl.dz extension)
:del_dict: ""
# e.g., to ignore two dictionaries called somedict.dsl.dz and 
# someotherdict.dsl.dz, uncomment the following line:
# :del_dict: "somedict","someotherdict"

# dsl markup options
# remove markup (i.e. all text between "[]" tags); default is to remove markup
:markup: '\[.*?\]'      # remove dsl markup
# :markup: ""   # example: uncomment to allow dsl markup in entries
:markup_replace: ""

# forvo key
# this key should be set in the user config file only
# :forvo_key: ""
